### ISSUE TITLE
Make getRoute more useful by outside consumers

### ISSUE THREAD

**Issue by markjaquith** [tsndr/cloudflare-worker-router#1]
`getRoute()` returns a route, but has side effects (setting `.params` on the passed in `request` argument). So that means you can't pass in an actual (or read-only) `Request` object, but instead have to construct this pseudo-`Request` object that your `handle()` method constructs. What if, instead, `getRoute()` returned the route and the params separately? Like as `{ route, params }`.

That'd allow me to more easily use the router portion of this while ignoring the `handle()` part, which doesn't really apply to my use cases.

Like this:

```js
import Router from '@tsndr/cloudflare-worker-router';
import * as handlers from './handlers';
import myHandlerManager from './myHandlerManager';

const router = new Router();

router.get('/test', handlers.testHandler);

addEventListener('fetch', event => {
  const { route, params } = router.getRoute(event.request);

  event.respondWith(myHandlerManager(event, route, params));
});
```

**Comment by tsndr** [comment]
I'm missing a bit of context here since I don't quite understand what `myHandlerManager` does and why it's necessary.

For my projects, I use the following architecture:

`src/controllers/ExampleController.js`
```javascript
module.exports = new class {

    async get(req, res) {
        // Get dataId from url
        const dataId = req.params.dataId

        // Fetching data from KV store
        const data = JSON.parse(await KV.get(dataId))

        // Return 404 if no data were found
        if (!data) {
            res.status = 404
            return
        }

        // Otherwise return data
        res.data = data
    }

}
```

`src/index.js`
```javascript
const Router = require('@tsndr/cloudflare-worker-router')
const router = new Router()
const ExampleController = require('./controllers/ExampleController')

router.cors()

// Routes
router.get('/v1/example/:dataId', ExampleController.get)

addEventListener('fetch', event => {
    event.respondWith(router.handle(event))
})
```

**Comment by markjaquith** [comment]
Mostly I come from the context of having an upstream server, not a purely serverless situation. Sure, sometimes I'll intercept an incoming request and "return early" a response (useful for redirects, 403s, etc). But largely I'm:

1. Modifying a request (adding/changing headers, modifying the URL, etc).
2. Performing a upstream fetch on the resulting request.
3. Modifying the response.
4. Giving that response back to Cloudflare for delivery.

So I don't just have request handlers, I also have response handlers, to finesse the data coming back from the upstream server. `myHandlerManager` would be applying multiple request handlers, doing `const response = await fetch(modifiedRequest);`, and then applying multiple response handlers to that response, before returning that response to Cloudflare for delivery.

You seem to have structured things with the assumption that people will be directly returning a `Response` from their request handler, and any `fetch()` that happens will have to be manually implemented within a request handler.

But I think we can separate the idea of a router from the idea of a request handler. It's really two steps:

1. The identification of the correct route and parameters.
2. Handling that route (and parameters) with the appropriate handlers.

We have different needs for step 2, but what I'm saying is that with some changes, we could share the code for step 1.

Annnd at this point of typing I saw that you saw my comment on Reddit. 😄 

If you don't want to accommodate the proxy workflow, no worries. It's a small amount of code, so it's trivial. And really, I *could* use it as-is. It just wouldn't be as elegant.

```js
const request = { headers: event.request.headers, method: event.request.method, url: event.request.url, params: [] };
const route = router.getRoute(request);
const { params } = request;
// Now I have `route`, `event.request`, and `params`.
```

Anyway, happy to find someone else who is as excited as I am about this stuff. 🤝

**Comment by tsndr** [comment]
I just looked into my code, and I don't think that I can implement it without impacting the 99% of other cases that don't need this behavior. Since I don't think that it makes sense to add the whole `route` with all its handlers to the `request` object I don't see an efficient way to accommodate your use case. If you have any idea that I don't see right now, please let me know, and we can work something out, until then your solution seems to me like the best I could come up with either.

**Comment by markjaquith** [comment]
Yep, no worries! I just made a derivative Router that works the way I need. https://github.com/markjaquith/cf-worker-utils/blob/main/src/Router.js

Some unit tests too: https://github.com/markjaquith/cf-worker-utils/blob/main/src/Router.test.js

Appreciate the head start. Having a working router is really gonna help me out.
