### ISSUE TITLE
Not working with custom domain

### ISSUE THREAD

**Issue by noman-land** [tsndr/cloudflare-worker-router#15]
I'm sure I'm doing something wrong with the config but when I test this with my `workers.dev` domain everything works flawlessly, however when I try to use the domain I have connected, the router returns all 404s. 

I know the request arrives at the worker since I see the call in the logs, on the custom domain, but the router doesn't seem to recognize the route for some reason.

**Comment by tsndr** [comment]
This router doesn't even care about the domain, so this has to be some kind of misconfiguration in your cloudflare dashboard, maybe you forgot to set the DNS records. With the information you gave here I can only guess.
