### ISSUE TITLE
Cloudflare Module Worker Example?

### ISSUE THREAD

**Issue by grempe** [tsndr/cloudflare-worker-router#18]
An example of using this with Module workers would be helpful.

https://developers.cloudflare.com/workers/learning/migrating-to-module-workers

**Comment by tsndr** [comment]
It's on my todo list, but I wasn't able to get to it yet.

**Comment by tsndr** [comment]
Quick update, I'm currently working on that:

https://github.com/tsndr/cloudflare-worker-router/tree/v2-pre

**Comment by tsndr** [comment]
https://github.com/tsndr/cloudflare-worker-router/releases/tag/v2.0.0
