### ISSUE TITLE
Consider dropping the `default` export in favor of named exports

### ISSUE THREAD

**Issue by AlCalzone** [tsndr/cloudflare-worker-router#22]
Currently when bundling this into a module worker using esbuild, the module including the default export gets wrapped again in `{default: /* original module */}`. Details why are explained here:
https://esbuild.github.io/content-types/#default-interop under "The Node interpretation"

As a result, one has to access the `Router` class using this awkward way
```ts
import Router_default from "@tsndr/cloudflare-worker-router";
const Router = Router_default.default;
```
which totally breaks down when needing types too.

To resolve this, I had to create a local copy, remove `default` from the export and import this way:
```ts
import { Router } from "./cloudflare-worker-router";
```

**Comment by tsndr** [comment]
Thank you for bringing this up, here you go: [v2.2.0](https://github.com/tsndr/cloudflare-worker-router/tree/v2.2.0)
