### ISSUE TITLE
When have global handlers, env seems not work

### ISSUE THREAD

**Issue by lljxx1** [tsndr/cloudflare-worker-router#27]
```typescript

router.use({ req, res, next }) => {
    if (!req.query.api_key) {
        req.body = {
            error: "key missing"
        }
        return;
    }
    next()
});


router.get("/check", async ({ env, req, res }) => {
    console.log(env.KV)
    console.log(await env.KV.get("test"))
})

```

When remove this, It's worked
```typescript

//router.use(authMiddleware);

router.get("/check", async ({ env, req, res }) => {
  // worked
   console.log(await env.KV.get("test"))
})
```

**Comment by tsndr** [comment]
Are you calling `next()` in your `authMiddleware`?

Example:
```typescript
router.use(({ req, res, next }) => {
    res.headers.set('X-Global-Middlewares', 'true')
    next()
})
```

**Comment by tsndr** [comment]
Also in your exammple you need to await `env.KV.get("test")` since it returns a promise.

**Comment by lljxx1** [comment]
> Are you calling `next()` in your `authMiddleware`?
> 
> Example:
> 
> ```ts
> router.use(({ req, res, next }) => {
>     res.headers.set('X-Global-Middlewares', 'true')
>     next()
> })
> ```

yeah, I did

**Comment by lljxx1** [comment]
> Also in your exammple you need to await `env.KV.get("test")` since it returns a promise.

yes. I have used `await` in my code. sorry for the demo

**Comment by lljxx1** [comment]
```typescript
router.use({ req, res, next }) => {
    if (!req.query.api_key) {
        req.body = {
            error: "key missing"
        }
        return;
    }
    next()
});


router.get("/check", async ({ env, req, res }) => {
    console.log(env.KV)
    console.log(await env.KV.get("test"))
})

```

**Comment by lljxx1** [comment]
`env.KV` is not undefined. just call `get` and will return nothing.
after a lot of bugging, if I comment `router.use` part. it will work.

**Comment by lljxx1** [comment]
@tsndr hey, have checked this issue by any chance? I still believe there have some problems here

**Comment by tsndr** [comment]
I'm finalizing `v3.0.0` right now, which is a partial rewrite and does things a little differently, should fix this issue.

You can take a look [here](https://github.com/tsndr/cloudflare-worker-router/tree/return-syntax), if you like, then you can try it out:
```sh
npm i -D @tsndr/cloudflare-worker-router@pre
```
