### ISSUE TITLE
async handlers in router.post do not seem to work

### ISSUE THREAD

**Issue by atsirigotis** [tsndr/cloudflare-worker-router#28]
Hi, thank you for providing this library, it is great. I m just starting with cloudflare workers and your library helps a lot. I need to access kv from inside router.post. E.g.

```
router.post('/business/:businessId/products/:productId', async ({req, res, next, env}) => {
	res.body = await env.kv_test84e.get('test');
});
```
but the resulting res.body is empty. In cloudflare dashboard though I see that a read operation takes place

The same async handler if used in router.use works great

**Comment by tsndr** [comment]
Hi, I've just released [v3.0.0](https://github.com/tsndr/cloudflare-worker-router/releases/tag/v3.0.0), which handles responses a little better, please refer to the [Migration Guide](https://github.com/tsndr/cloudflare-worker-router/blob/e28976a4b6633d76fdc224004a435aa47b389158/MIGRATION.md) and check if that would fix your issue :)

**Comment by rdbisme** [comment]
Hello, I have a similar problem: 

```
router.post('/webhook', ({ env, ctx, req }) => {
	console.log(req.body);
// ...
}
```

this logs `undefined`

**Comment by rdbisme** [comment]
This works (i.e. making the handler async and awaiting on `req.json()` or `req.text()`). 

```
router.post('/webhook', async ({ env, ctx, req }) => {
	let payload = await req.json();
```

**Comment by tsndr** [comment]
I will update the docs to make it more clear. I'm also working on an example project. In the meantime TypeScript should provide the correct autocompletes.
