### ISSUE TITLE
there's no body field in Request

### ISSUE THREAD

**Issue by jlcastillo** [tsndr/cloudflare-worker-router#36]
The body field is mentioned in the documentation but I didn't see it neither in types nor in the implementation. I wonder how people are getting contents of a POST, PUT, etc.

**Comment by Kain-90** [comment]
The `tests/index.spec.ts` file contains the unit test of `describe('Body', () => {`, including `await req.json()`, which can obtain the content in `application/json` body data. I hope it works for you
