### ISSUE TITLE
Doc suggests install as a devDependency?

### ISSUE THREAD

**Issue by grokwich** [tsndr/cloudflare-worker-router#38]
Is the following doc correct?

I assume the full lib should be installed (not -D)?

Thx.

> Getting started
> Please follow Cloudflare's [Get started guide](https://developers.cloudflare.com/workers/get-started/guide/) to install wrangler.
> 
> Initialize Project
> wrangler init <name>
> Use of TypeScript is strongly encouraged :)
> 
> npm i -D @tsndr/cloudflare-worker-router

**Comment by tsndr** [comment]
I think you're right. I'm gonna change it :)
