### ISSUE TITLE
Router not able to be imported into ESM worker after upgrade from v3.2.4 to v3.2.8

### ISSUE THREAD

**Issue by ffaubert** [tsndr/cloudflare-worker-router#40]
My worker is a esm module and was working fine with v3.2.4. I upgraded to v3.2.8, without making any other changes, and I get this error:

▲ [WARNING] Import "Router" will always be undefined because the file "../../node_modules/@tsndr/cloudflare-worker-router/index.js" has no exports [import-is-undefined]

    src/cdn.js:2:9:
      2 │ import { Router } from "@tsndr/cloudflare-worker-router";
        ╵          ~~~~~~

**Comment by tsndr** [comment]
Thanks for letting me know, I'll check and report back :)

**Comment by pooriaarab** [comment]
> Thanks for letting me know, I'll check and report back :)

Heyy @tsndr is there any way we can help fix the bug? when I run wrangler deploy it hits me up with the same error: 

export 'Router' (imported as 'Router') was not found in '@tsndr/cloudflare-worker-router' (module has no exports)

**Comment by nmthangdn2000** [comment]
I also got the same error when upgrading

**Comment by pooriaarab** [comment]
I switched to Hono and it works like a charm now

**Comment by nmthangdn2000** [comment]
I'm looking for a lightweight library that meets my needs, a good and lightweight alternative is [itty-router](https://www.npmjs.com/package/itty-router/v/4.2.1) 

I still hope the above bug is fixed soon

**Comment by pooriaarab** [comment]
itty router hasn’t been updated for 6 months

**Comment by tsndr** [comment]
Fixed with [v3.2.9](https://github.com/tsndr/cloudflare-worker-router/releases/tag/v3.2.9)
