### ISSUE TITLE
`query` property of RouterRequest has no TS definition?

### ISSUE THREAD

**Issue by colecrouter** [tsndr/cloudflare-worker-router#8]
https://github.com/tsndr/cloudflare-worker-router/blob/ec9f99e1327800ba50eeca957fc427d3443a2f0d/index.d.ts#L261

I'm not sure if I'm just missing something or not, but it seems like it should be there. Let me know if I'm wrong.

**Comment by tsndr** [comment]
It's right [here](https://github.com/tsndr/cloudflare-worker-router/blob/ec9f99e1327800ba50eeca957fc427d3443a2f0d/index.d.ts#L45) :)
